[features]
seeds = false
[programs.localnet]
amm = "DQsAkHhyHJhQ5tHjLFqyBh5XHUEWQbD9fgQPkvV9JGZc"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/localnet.json"

[scripts]
amm = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/amm.ts"
